export const resumeStorageKey = "job-agent.resume.items";

export const sources = [
  { id: 1, name: "国资委央企招聘", type: "央国企" },
  { id: 2, name: "Boss直聘", type: "综合招聘" },
  { id: 3, name: "猎聘网", type: "中高端岗位" },
  { id: 4, name: "企业官网", type: "官方校招" },
  { id: 5, name: "微信公众号", type: "垂直渠道" },
  { id: 6, name: "国聘网", type: "国企招聘" },
];

export const jobs = [
  {
    id: 1,
    title: "前端开发工程师",
    company: "方舟人才科技",
    city: "杭州",
    degree: "本科",
    match: 94,
    source: "企业官网",
    salary: "18-28K",
  },
  {
    id: 2,
    title: "AI Agent 产品研发",
    company: "蓝港智能",
    city: "上海",
    degree: "本科",
    match: 91,
    source: "Boss直聘",
    salary: "20-35K",
  },
  {
    id: 3,
    title: "React 工程师",
    company: "云岚科技",
    city: "北京",
    degree: "硕士",
    match: 87,
    source: "猎聘网",
    salary: "22-32K",
  },
  {
    id: 4,
    title: "机械设备工程师",
    company: "中航装备",
    city: "武汉",
    degree: "本科",
    match: 83,
    source: "国资委央企招聘",
    salary: "12-18K",
  },
  {
    id: 5,
    title: "数据分析工程师",
    company: "星河数科",
    city: "深圳",
    degree: "本科",
    match: 89,
    source: "微信公众号",
    salary: "16-26K",
  },
];

export const filterOptions = {
  cities: ["全国", "杭州", "上海", "北京", "武汉", "深圳"],
  degrees: ["不限", "本科", "硕士"],
  cohorts: ["26届", "25届", "社招"],
};

export const roles = [
  "软件开发工程师",
  "数据分析师",
  "人工智能工程师",
  "云计算工程师",
  "网络工程师",
  "前端开发",
  "后端开发",
  "Java开发",
  "Python开发",
  "Android开发",
  "iOS开发",
  "游戏开发",
  "网络安全分析师",
  "测试工程师",
  "项目经理",
  "产品经理",
  "产品运营",
  "新媒体运营",
  "内容运营",
  "运营专员",
  "UI设计师",
  "平面设计师",
  "设计师",
  "财务",
  "会计",
  "人力资源专员",
  "法务专员",
  "投资顾问",
  "审计",
  "金融分析师",
  "市场分析师",
  "市场营销专员",
  "销售代表",
  "物流专员",
  "客服专员",
  "公共关系专员",
  "化学工程师",
  "生物技术研究员",
  "土木工程师",
  "建筑设计师",
  "环境科学家",
  "机械工程师",
  "工业工程师",
  "电气工程师",
  "硬件工程师",
];
